export const GEOMETRY_SERVICE_CONTRACT_VERSION = 10 as const;

export {
  alignItems,
  distributeItems,
  MAX_ARRANGEMENT_SPACING,
  measureItemSpacing,
  setItemSpacing,
  tidyUpItems,
  type AlignAction,
  type ArrangeAxis,
  type ArrangementFailure,
  type ArrangementFailureCode,
  type ArrangementItem,
  type ArrangementPlacement,
  type ArrangementPlan,
  type SpacingMeasurement,
  type TidyUpDimension,
  type TidyUpPlacement,
  type TidyUpPlan,
} from "./arrangement.js";
export {
  cutVectorNetworkByLine,
  cutVectorPath,
  deleteVectorVertices,
  findVectorPathIdForVertex,
  inferVectorPointMode,
  listVectorVertexHandles,
  moveVectorHandle,
  moveVectorVertices,
  nearestVectorSegmentPoint,
  reverseVectorPath,
  setVectorPathClosed,
  setVectorPointMode,
  vectorNetworkEditability,
  type VectorCutLocation,
  type VectorCutResult,
  type VectorDeleteResult,
  type VectorEditFailureCode,
  type VectorEditResult,
  type VectorHandleReference,
  type VectorHandleSide,
  type VectorLineCutIntersection,
  type VectorLineCutResult,
  type VectorSegmentHit,
  type VectorVertexHandle,
} from "./vector-edit.js";
