export const DESIGN_SCHEMA_VERSION = "1.20.0" as const;
export const LAYOUT_GUIDE_COLUMNS_ROWS_DESIGN_SCHEMA_VERSION =
  "1.20.0" as const;
export const LAYOUT_GUIDE_DESIGN_SCHEMA_VERSION = "1.19.0" as const;
export const AUTO_LAYOUT_ABSOLUTE_CHILD_DESIGN_SCHEMA_VERSION =
  "1.18.0" as const;
export const AUTO_LAYOUT_AUTO_GAP_DESIGN_SCHEMA_VERSION = "1.17.0" as const;
export const AUTO_LAYOUT_LIMITS_DESIGN_SCHEMA_VERSION = "1.16.0" as const;
export const AUTO_LAYOUT_WRAP_DESIGN_SCHEMA_VERSION = "1.15.0" as const;
export const AUTO_LAYOUT_SIZING_DESIGN_SCHEMA_VERSION = "1.14.0" as const;
export const LINEAR_AUTO_LAYOUT_DESIGN_SCHEMA_VERSION = "1.13.0" as const;
export const FRAME_CONSTRAINTS_DESIGN_SCHEMA_VERSION = "1.12.0" as const;
export const COMPONENT_DESIGN_SCHEMA_VERSION = "1.11.0" as const;
export const ADVANCED_VECTOR_CUT_DESIGN_SCHEMA_VERSION = "1.10.0" as const;
export const TEXT_LAYOUT_DESIGN_SCHEMA_VERSION = "1.9.0" as const;
export const VECTOR_POINT_EDITING_DESIGN_SCHEMA_VERSION = "1.8.0" as const;
export const EDITABLE_VECTOR_DESIGN_SCHEMA_VERSION = "1.7.0" as const;
export const REGULAR_SHAPE_DESIGN_SCHEMA_VERSION = "1.6.0" as const;
export const LINE_DESIGN_SCHEMA_VERSION = "1.5.0" as const;
export const MASK_DESIGN_SCHEMA_VERSION = "1.4.0" as const;
export const IMAGE_PLACEMENT_DESIGN_SCHEMA_VERSION = "1.3.0" as const;
export const PATH_DESIGN_SCHEMA_VERSION = "1.2.0" as const;
export const APPEARANCE_DESIGN_SCHEMA_VERSION = "1.1.0" as const;
export const LEGACY_DESIGN_SCHEMA_VERSION = "1.0.0" as const;

export const MIGRATABLE_DESIGN_SCHEMA_VERSIONS: readonly string[] = [
  LEGACY_DESIGN_SCHEMA_VERSION,
  APPEARANCE_DESIGN_SCHEMA_VERSION,
  PATH_DESIGN_SCHEMA_VERSION,
  IMAGE_PLACEMENT_DESIGN_SCHEMA_VERSION,
  MASK_DESIGN_SCHEMA_VERSION,
  LINE_DESIGN_SCHEMA_VERSION,
  REGULAR_SHAPE_DESIGN_SCHEMA_VERSION,
  EDITABLE_VECTOR_DESIGN_SCHEMA_VERSION,
  VECTOR_POINT_EDITING_DESIGN_SCHEMA_VERSION,
  TEXT_LAYOUT_DESIGN_SCHEMA_VERSION,
  ADVANCED_VECTOR_CUT_DESIGN_SCHEMA_VERSION,
  COMPONENT_DESIGN_SCHEMA_VERSION,
  FRAME_CONSTRAINTS_DESIGN_SCHEMA_VERSION,
  LINEAR_AUTO_LAYOUT_DESIGN_SCHEMA_VERSION,
  AUTO_LAYOUT_SIZING_DESIGN_SCHEMA_VERSION,
  AUTO_LAYOUT_WRAP_DESIGN_SCHEMA_VERSION,
  AUTO_LAYOUT_LIMITS_DESIGN_SCHEMA_VERSION,
  AUTO_LAYOUT_AUTO_GAP_DESIGN_SCHEMA_VERSION,
  AUTO_LAYOUT_ABSOLUTE_CHILD_DESIGN_SCHEMA_VERSION,
  LAYOUT_GUIDE_DESIGN_SCHEMA_VERSION,
];
