export const DESIGN_SCHEMA_VERSION = "1.44.0" as const;
export const IMAGE_RELIGHTING_DESIGN_SCHEMA_VERSION = "1.44.0" as const;
export const IMAGE_BACKGROUND_REPLACEMENT_DESIGN_SCHEMA_VERSION =
  "1.43.0" as const;
export const IMAGE_ASSET_DERIVATIONS_DESIGN_SCHEMA_VERSION = "1.42.0" as const;
export const IMAGE_PAINT_ADJUSTMENTS_DESIGN_SCHEMA_VERSION = "1.41.0" as const;
export const IMAGE_ADJUSTMENTS_DESIGN_SCHEMA_VERSION = "1.40.0" as const;
export const LIBRARY_VARIABLE_SOURCE_DESIGN_SCHEMA_VERSION = "1.39.0" as const;
export const LIBRARY_STYLE_SOURCE_DESIGN_SCHEMA_VERSION = "1.38.0" as const;
export const LIBRARY_COMPONENT_SOURCE_DESIGN_SCHEMA_VERSION = "1.37.0" as const;
export const FIGMA_LAYER_STATE_DESIGN_SCHEMA_VERSION = "1.36.0" as const;
export const AUTO_LAYOUT_GRID_V2_DESIGN_SCHEMA_VERSION = "1.35.0" as const;
export const AUTO_LAYOUT_GRID_DESIGN_SCHEMA_VERSION = "1.34.0" as const;
export const FIGMA_TEXT_LISTS_DESIGN_SCHEMA_VERSION = "1.33.0" as const;
export const PARAGRAPH_STYLE_RUNS_DESIGN_SCHEMA_VERSION = "1.32.0" as const;
export const RICH_TEXT_RUNS_DESIGN_SCHEMA_VERSION = "1.31.0" as const;
export const FONT_FACE_IDENTITY_DESIGN_SCHEMA_VERSION = "1.30.0" as const;
export const TYPOGRAPHY_CORE_V2_DESIGN_SCHEMA_VERSION = "1.29.0" as const;
export const FIGMA_EXPORT_SETTINGS_DESIGN_SCHEMA_VERSION = "1.28.0" as const;
export const FIGMA_SHARED_STYLES_DESIGN_SCHEMA_VERSION = "1.27.0" as const;
export const FIGMA_VARIABLES_DESIGN_SCHEMA_VERSION = "1.26.0" as const;
export const COMPONENT_PROPERTY_ORDER_DESIGN_SCHEMA_VERSION = "1.25.0" as const;
export const COMPONENT_SLOT_DESIGN_SCHEMA_VERSION = "1.24.0" as const;
export const VARIANT_PROPERTY_MATRIX_DESIGN_SCHEMA_VERSION = "1.23.0" as const;
export const COMPONENT_SET_VARIANT_DESIGN_SCHEMA_VERSION = "1.22.0" as const;
export const FIGMA_COMPONENT_PROPERTIES_DESIGN_SCHEMA_VERSION =
  "1.21.0" as const;
export const LAYOUT_GUIDE_COLUMNS_ROWS_DESIGN_SCHEMA_VERSION =
  "1.20.0" as const;
export const LAYOUT_GUIDE_DESIGN_SCHEMA_VERSION = "1.19.0" as const;
export const AUTO_LAYOUT_ABSOLUTE_CHILD_DESIGN_SCHEMA_VERSION =
  "1.18.0" as const;
export const AUTO_LAYOUT_AUTO_GAP_DESIGN_SCHEMA_VERSION = "1.17.0" as const;
export const AUTO_LAYOUT_LIMITS_DESIGN_SCHEMA_VERSION = "1.16.0" as const;
export const AUTO_LAYOUT_WRAP_DESIGN_SCHEMA_VERSION = "1.15.0" as const;
export const AUTO_LAYOUT_SIZING_DESIGN_SCHEMA_VERSION = "1.14.0" as const;
export const LINEAR_AUTO_LAYOUT_DESIGN_SCHEMA_VERSION = "1.13.0" as const;
export const FRAME_CONSTRAINTS_DESIGN_SCHEMA_VERSION = "1.12.0" as const;
export const COMPONENT_DESIGN_SCHEMA_VERSION = "1.11.0" as const;
export const ADVANCED_VECTOR_CUT_DESIGN_SCHEMA_VERSION = "1.10.0" as const;
export const TEXT_LAYOUT_DESIGN_SCHEMA_VERSION = "1.9.0" as const;
export const VECTOR_POINT_EDITING_DESIGN_SCHEMA_VERSION = "1.8.0" as const;
export const EDITABLE_VECTOR_DESIGN_SCHEMA_VERSION = "1.7.0" as const;
export const REGULAR_SHAPE_DESIGN_SCHEMA_VERSION = "1.6.0" as const;
export const LINE_DESIGN_SCHEMA_VERSION = "1.5.0" as const;
export const MASK_DESIGN_SCHEMA_VERSION = "1.4.0" as const;
export const IMAGE_PLACEMENT_DESIGN_SCHEMA_VERSION = "1.3.0" as const;
export const PATH_DESIGN_SCHEMA_VERSION = "1.2.0" as const;
export const APPEARANCE_DESIGN_SCHEMA_VERSION = "1.1.0" as const;
export const LEGACY_DESIGN_SCHEMA_VERSION = "1.0.0" as const;

export const MIGRATABLE_DESIGN_SCHEMA_VERSIONS: readonly string[] = [
  LEGACY_DESIGN_SCHEMA_VERSION,
  APPEARANCE_DESIGN_SCHEMA_VERSION,
  PATH_DESIGN_SCHEMA_VERSION,
  IMAGE_PLACEMENT_DESIGN_SCHEMA_VERSION,
  MASK_DESIGN_SCHEMA_VERSION,
  LINE_DESIGN_SCHEMA_VERSION,
  REGULAR_SHAPE_DESIGN_SCHEMA_VERSION,
  EDITABLE_VECTOR_DESIGN_SCHEMA_VERSION,
  VECTOR_POINT_EDITING_DESIGN_SCHEMA_VERSION,
  TEXT_LAYOUT_DESIGN_SCHEMA_VERSION,
  ADVANCED_VECTOR_CUT_DESIGN_SCHEMA_VERSION,
  COMPONENT_DESIGN_SCHEMA_VERSION,
  FRAME_CONSTRAINTS_DESIGN_SCHEMA_VERSION,
  LINEAR_AUTO_LAYOUT_DESIGN_SCHEMA_VERSION,
  AUTO_LAYOUT_SIZING_DESIGN_SCHEMA_VERSION,
  AUTO_LAYOUT_WRAP_DESIGN_SCHEMA_VERSION,
  AUTO_LAYOUT_LIMITS_DESIGN_SCHEMA_VERSION,
  AUTO_LAYOUT_AUTO_GAP_DESIGN_SCHEMA_VERSION,
  AUTO_LAYOUT_ABSOLUTE_CHILD_DESIGN_SCHEMA_VERSION,
  LAYOUT_GUIDE_DESIGN_SCHEMA_VERSION,
  LAYOUT_GUIDE_COLUMNS_ROWS_DESIGN_SCHEMA_VERSION,
  FIGMA_COMPONENT_PROPERTIES_DESIGN_SCHEMA_VERSION,
  COMPONENT_SET_VARIANT_DESIGN_SCHEMA_VERSION,
  VARIANT_PROPERTY_MATRIX_DESIGN_SCHEMA_VERSION,
  COMPONENT_SLOT_DESIGN_SCHEMA_VERSION,
  COMPONENT_PROPERTY_ORDER_DESIGN_SCHEMA_VERSION,
  FIGMA_VARIABLES_DESIGN_SCHEMA_VERSION,
  FIGMA_SHARED_STYLES_DESIGN_SCHEMA_VERSION,
  FIGMA_EXPORT_SETTINGS_DESIGN_SCHEMA_VERSION,
  TYPOGRAPHY_CORE_V2_DESIGN_SCHEMA_VERSION,
  FONT_FACE_IDENTITY_DESIGN_SCHEMA_VERSION,
  RICH_TEXT_RUNS_DESIGN_SCHEMA_VERSION,
  PARAGRAPH_STYLE_RUNS_DESIGN_SCHEMA_VERSION,
  FIGMA_TEXT_LISTS_DESIGN_SCHEMA_VERSION,
  AUTO_LAYOUT_GRID_DESIGN_SCHEMA_VERSION,
  AUTO_LAYOUT_GRID_V2_DESIGN_SCHEMA_VERSION,
  FIGMA_LAYER_STATE_DESIGN_SCHEMA_VERSION,
  LIBRARY_COMPONENT_SOURCE_DESIGN_SCHEMA_VERSION,
  LIBRARY_STYLE_SOURCE_DESIGN_SCHEMA_VERSION,
  LIBRARY_VARIABLE_SOURCE_DESIGN_SCHEMA_VERSION,
  IMAGE_ADJUSTMENTS_DESIGN_SCHEMA_VERSION,
  IMAGE_PAINT_ADJUSTMENTS_DESIGN_SCHEMA_VERSION,
  IMAGE_ASSET_DERIVATIONS_DESIGN_SCHEMA_VERSION,
  IMAGE_BACKGROUND_REPLACEMENT_DESIGN_SCHEMA_VERSION,
];
