import type {
  ToolCallRequest,
  TrustedToolContext,
  TrustedToolResult,
} from "@opendesign/agent-contracts";
import { beforeEach, describe, expect, it, vi } from "vitest";
import {
  EDIT_IMAGE_TOOL_NAME,
  GENERATE_IMAGE_TOOL_NAME,
  INTERNAL_DESIGN_APPLY_TOOL_NAME,
  type InternalDesignApplyToolInput,
  PLACE_IMAGE_TOOL_NAME,
  READ_IMAGE_TOOL_NAME,
} from "@/shared/design-agent-tools.js";
import { handleDesignImageTool } from "./design-image-tool-handler.js";

vi.mock("electron", () => ({
  nativeImage: {
    createFromBuffer: () => ({
      getSize: () => ({ width: 1536, height: 1024 }),
    }),
  },
}));

const context: TrustedToolContext = {
  runId: "run_image",
  sessionId: "conversation_image",
  documentId: "document_image",
  revision: 3,
  scope: { kind: "page", pageId: "page_main", selectedNodeIds: [] },
  mutationTarget: { kind: "page", pageId: "page_main" },
};

function dependencies(call: ToolCallRequest) {
  const coordinator = {
    assertDocumentInspected: vi.fn(),
    assertDesignPlanForRaster: vi.fn(),
    recordGeneratedRaster: vi.fn(),
    recordMaterialDesignWriteCompleted: vi.fn(),
    assertImagePlacement: vi.fn(),
    resolveMaterialTargetIdsIfPlanned: vi.fn(() => []),
  };
  const attachment = {
    attachmentId: `image_${"a".repeat(64)}`,
    name: "generated-image.webp",
    mimeType: "image/webp" as const,
    byteSize: 4,
  };
  const attachmentHost = {
    importImageBytes: vi.fn().mockResolvedValue(attachment),
  };
  const referenceHost = {
    readImage: vi.fn(),
    registerGeneratedImage: vi.fn((value: typeof attachment) => value),
    hasAuthorizedImage: vi.fn(() => true),
    materializeImage: vi.fn().mockResolvedValue({
      attachment,
      data: Buffer.from([1, 2, 3, 4]).toString("base64"),
      mimeType: "image/webp" as const,
    }),
  };
  const imageGenerationHost = {
    generateImage: vi.fn().mockResolvedValue({
      bytes: new Uint8Array([1, 2, 3, 4]),
      apiFormat: "openai-images",
      modelId: "gpt-image-2",
      providerRequestId: "provider_request",
      size: "1536x1024",
      quality: "high",
      outputFormat: "webp",
    }),
  };
  const execute = vi
    .fn<(call: ToolCallRequest) => Promise<TrustedToolResult>>()
    .mockResolvedValue({
      content: { ok: true },
      designRevision: {
        previousRevision: 3,
        revision: 4,
        transactionId: "stage_asset",
      },
    });
  const withDelivery = vi.fn((result: TrustedToolResult) => result);
  const imageEditService = { edit: vi.fn() };

  return {
    input: {
      call,
      context,
      executionContext: context,
      signal: new AbortController().signal,
      coordinator: coordinator as never,
      getAttachmentHost: vi.fn(() => attachmentHost as never),
      getReferenceHost: vi.fn(() => referenceHost as never),
      getImageGenerationHost: vi.fn(() => imageGenerationHost as never),
      imageEditService: imageEditService as never,
      execute,
      withDelivery,
    },
    attachment,
    attachmentHost,
    coordinator,
    execute,
    imageGenerationHost,
    imageEditService,
    referenceHost,
  };
}

describe("Design Image Main tool handler", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns null without touching dependencies for another tool family", async () => {
    const setup = dependencies({
      toolCallId: "other_tool",
      toolName: "opendesign_inspect_document",
      input: {},
    });

    await expect(handleDesignImageTool(setup.input)).resolves.toBeNull();
    expect(setup.execute).not.toHaveBeenCalled();
    expect(setup.imageGenerationHost.generateImage).not.toHaveBeenCalled();
    expect(setup.input.getAttachmentHost).not.toHaveBeenCalled();
    expect(setup.input.getReferenceHost).not.toHaveBeenCalled();
    expect(setup.input.getImageGenerationHost).not.toHaveBeenCalled();
  });

  it("routes read-image through the Run-bound reference host", async () => {
    const call: ToolCallRequest = {
      toolCallId: "read_image",
      toolName: READ_IMAGE_TOOL_NAME,
      input: { source: "/tmp/reference.png" },
    };
    const setup = dependencies(call);
    const result: TrustedToolResult = { content: { ok: true } };
    setup.referenceHost.readImage.mockResolvedValue(result);

    await expect(handleDesignImageTool(setup.input)).resolves.toBe(result);
    expect(setup.referenceHost.readImage).toHaveBeenCalledWith(
      { source: "/tmp/reference.png" },
      context,
      setup.input.signal,
    );
    expect(setup.execute).not.toHaveBeenCalled();
  });

  it("stages generated bytes as a persistent Design File asset", async () => {
    const call: ToolCallRequest = {
      toolCallId: "generate_hero",
      toolName: GENERATE_IMAGE_TOOL_NAME,
      input: {
        prompt: "A precise editorial hero image",
        role: "hero",
        size: "1536x1024",
        quality: "high",
        outputFormat: "webp",
      },
    };
    const setup = dependencies(call);

    const result = await handleDesignImageTool(setup.input);

    expect(setup.coordinator.assertDesignPlanForRaster).toHaveBeenCalledWith(
      context,
      "hero",
    );
    expect(setup.attachmentHost.importImageBytes).toHaveBeenCalledWith(
      "generated-image.webp",
      new Uint8Array([1, 2, 3, 4]),
    );
    expect(setup.referenceHost.registerGeneratedImage).toHaveBeenCalledWith(
      setup.attachment,
      context,
    );
    const executed = setup.execute.mock.calls[0]?.[0];
    expect(executed?.toolName).toBe(INTERNAL_DESIGN_APPLY_TOOL_NAME);
    expect(executed?.input).toMatchObject({
      commands: [
        {
          type: "put_asset",
          asset: {
            id: `asset_${"a".repeat(64)}`,
            mimeType: "image/webp",
            size: { width: 1536, height: 1024 },
          },
        },
      ],
    });
    expect(setup.coordinator.recordGeneratedRaster).toHaveBeenCalledWith(
      context,
      setup.attachment.attachmentId,
      "hero",
    );
    expect(result).toMatchObject({
      content: {
        ok: true,
        sourceKind: "generated",
        asset: {
          assetId: `asset_${"a".repeat(64)}`,
          scope: "design-file",
        },
      },
      designRevision: { revision: 4 },
    });
  });

  it("places a Conversation image without requiring a design Plan", async () => {
    const call: ToolCallRequest = {
      toolCallId: "place_history_image",
      toolName: PLACE_IMAGE_TOOL_NAME,
      input: {
        attachmentId: `image_${"a".repeat(64)}`,
        pageId: "page_main",
        parentId: "existing_frame",
        index: 0,
        nodeId: "history_hero",
        name: "History hero",
        role: "hero",
        x: 24,
        y: 24,
        width: 720,
        height: 480,
      },
    };
    const setup = dependencies(call);

    await expect(handleDesignImageTool(setup.input)).resolves.toMatchObject({
      designRevision: { revision: 4 },
    });
    expect(setup.coordinator.assertImagePlacement).toHaveBeenCalledWith(
      context,
      "existing_frame",
      "history_hero",
    );
    expect(
      setup.coordinator.resolveMaterialTargetIdsIfPlanned,
    ).toHaveBeenCalledWith(context, [], "existing_frame");
    const executed = setup.execute.mock.calls[0]?.[0];
    expect(executed?.toolName).toBe(INTERNAL_DESIGN_APPLY_TOOL_NAME);
    const input = executed?.input as InternalDesignApplyToolInput;
    const inserted = input.commands.find(
      (command) => command.type === "insert_element",
    );
    expect(inserted?.type).toBe("insert_element");
    if (inserted?.type !== "insert_element") return;
    expect(inserted.node).toMatchObject({ id: "history_hero", kind: "image" });
  });

  it("returns the prepared image source field path before external editing", async () => {
    const assetId = `asset_${"b".repeat(64)}`;
    const setup = dependencies({
      toolCallId: "remove_background",
      toolName: EDIT_IMAGE_TOOL_NAME,
      input: {
        action: "remove-background",
        label: "Remove background",
        pageId: "page_main",
        nodeId: "hero_image",
        expectedAssetId: assetId,
      },
    });
    setup.execute.mockResolvedValueOnce({
      observedRevision: 3,
      content: {
        kind: "prepared-image-edit-source",
        pageId: "page_main",
        nodeId: "hero_image",
        expectedAssetId: assetId,
        asset: {
          id: assetId,
          kind: "image",
          name: "Hero.png",
          mimeType: "image/png",
          source: { type: "external", value: "/tmp/hero.png" },
          size: { width: 1600, height: 900 },
          extensions: {},
        },
        placement: { mode: "fit" },
        targetSize: { width: 800, height: 450 },
      },
    });

    await expect(handleDesignImageTool(setup.input)).rejects.toThrow(
      /Image edit source preparation.*\/asset\/source\/type/,
    );
    expect(setup.imageEditService.edit).not.toHaveBeenCalled();
  });
});
