import type {
  ToolCallRequest,
  TrustedToolContext,
  TrustedToolResult,
} from "@opendesign/agent-contracts";
import { beforeEach, describe, expect, it, vi } from "vitest";
import {
  GENERATE_IMAGE_TOOL_NAME,
  INTERNAL_DESIGN_APPLY_TOOL_NAME,
  READ_IMAGE_TOOL_NAME,
} from "@/shared/design-agent-tools.js";
import { handleDesignImageTool } from "./design-image-tool-handler.js";

vi.mock("electron", () => ({
  nativeImage: {
    createFromBuffer: () => ({
      getSize: () => ({ width: 1536, height: 1024 }),
    }),
  },
}));

const context: TrustedToolContext = {
  runId: "run_image",
  sessionId: "conversation_image",
  documentId: "document_image",
  revision: 3,
  scope: { kind: "page", pageId: "page_main", selectedNodeIds: [] },
  mutationTarget: { kind: "page", pageId: "page_main" },
};

function dependencies(call: ToolCallRequest) {
  const coordinator = {
    assertDesignPlanForRaster: vi.fn(),
    recordGeneratedRaster: vi.fn(),
  };
  const attachment = {
    attachmentId: `image_${"a".repeat(64)}`,
    name: "generated-image.webp",
    mimeType: "image/webp" as const,
    byteSize: 4,
  };
  const attachmentHost = {
    importImageBytes: vi.fn().mockResolvedValue(attachment),
  };
  const referenceHost = {
    readImage: vi.fn(),
    registerGeneratedImage: vi.fn((value: typeof attachment) => value),
  };
  const imageGenerationHost = {
    generateImage: vi.fn().mockResolvedValue({
      bytes: new Uint8Array([1, 2, 3, 4]),
      apiFormat: "openai-images",
      modelId: "gpt-image-2",
      providerRequestId: "provider_request",
      size: "1536x1024",
      quality: "high",
      outputFormat: "webp",
    }),
  };
  const execute = vi
    .fn<(call: ToolCallRequest) => Promise<TrustedToolResult>>()
    .mockResolvedValue({
      content: { ok: true },
      designRevision: {
        previousRevision: 3,
        revision: 4,
        transactionId: "stage_asset",
      },
    });
  const withDelivery = vi.fn((result: TrustedToolResult) => result);

  return {
    input: {
      call,
      context,
      executionContext: context,
      signal: new AbortController().signal,
      coordinator: coordinator as never,
      getAttachmentHost: vi.fn(() => attachmentHost as never),
      getReferenceHost: vi.fn(() => referenceHost as never),
      getImageGenerationHost: vi.fn(() => imageGenerationHost as never),
      imageEditService: {} as never,
      execute,
      withDelivery,
    },
    attachment,
    attachmentHost,
    coordinator,
    execute,
    imageGenerationHost,
    referenceHost,
  };
}

describe("Design Image Main tool handler", () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it("returns null without touching dependencies for another tool family", async () => {
    const setup = dependencies({
      toolCallId: "other_tool",
      toolName: "opendesign_inspect_document",
      input: {},
    });

    await expect(handleDesignImageTool(setup.input)).resolves.toBeNull();
    expect(setup.execute).not.toHaveBeenCalled();
    expect(setup.imageGenerationHost.generateImage).not.toHaveBeenCalled();
    expect(setup.input.getAttachmentHost).not.toHaveBeenCalled();
    expect(setup.input.getReferenceHost).not.toHaveBeenCalled();
    expect(setup.input.getImageGenerationHost).not.toHaveBeenCalled();
  });

  it("routes read-image through the Run-bound reference host", async () => {
    const call: ToolCallRequest = {
      toolCallId: "read_image",
      toolName: READ_IMAGE_TOOL_NAME,
      input: { source: "/tmp/reference.png" },
    };
    const setup = dependencies(call);
    const result: TrustedToolResult = { content: { ok: true } };
    setup.referenceHost.readImage.mockResolvedValue(result);

    await expect(handleDesignImageTool(setup.input)).resolves.toBe(result);
    expect(setup.referenceHost.readImage).toHaveBeenCalledWith(
      { source: "/tmp/reference.png" },
      context,
      setup.input.signal,
    );
    expect(setup.execute).not.toHaveBeenCalled();
  });

  it("stages generated bytes as a persistent Design File asset", async () => {
    const call: ToolCallRequest = {
      toolCallId: "generate_hero",
      toolName: GENERATE_IMAGE_TOOL_NAME,
      input: {
        prompt: "A precise editorial hero image",
        role: "hero",
        size: "1536x1024",
        quality: "high",
        outputFormat: "webp",
      },
    };
    const setup = dependencies(call);

    const result = await handleDesignImageTool(setup.input);

    expect(setup.coordinator.assertDesignPlanForRaster).toHaveBeenCalledWith(
      context,
      "hero",
    );
    expect(setup.attachmentHost.importImageBytes).toHaveBeenCalledWith(
      "generated-image.webp",
      new Uint8Array([1, 2, 3, 4]),
    );
    expect(setup.referenceHost.registerGeneratedImage).toHaveBeenCalledWith(
      setup.attachment,
      context,
    );
    const executed = setup.execute.mock.calls[0]?.[0];
    expect(executed?.toolName).toBe(INTERNAL_DESIGN_APPLY_TOOL_NAME);
    expect(executed?.input).toMatchObject({
      commands: [
        {
          type: "put_asset",
          asset: {
            id: `asset_${"a".repeat(64)}`,
            mimeType: "image/webp",
            size: { width: 1536, height: 1024 },
          },
        },
      ],
    });
    expect(setup.coordinator.recordGeneratedRaster).toHaveBeenCalledWith(
      context,
      setup.attachment.attachmentId,
      "hero",
    );
    expect(result).toMatchObject({
      content: {
        ok: true,
        sourceKind: "generated",
        asset: {
          assetId: `asset_${"a".repeat(64)}`,
          scope: "design-file",
        },
      },
      designRevision: { revision: 4 },
    });
  });

  it("rejects malformed generation input before calling external services", async () => {
    const setup = dependencies({
      toolCallId: "invalid_generate",
      toolName: GENERATE_IMAGE_TOOL_NAME,
      input: { prompt: "Too large", role: "hero", size: "8192x8192" },
    });

    await expect(handleDesignImageTool(setup.input)).rejects.toThrow(
      /generate_image.*size/i,
    );
    expect(setup.imageGenerationHost.generateImage).not.toHaveBeenCalled();
    expect(setup.attachmentHost.importImageBytes).not.toHaveBeenCalled();
    expect(setup.execute).not.toHaveBeenCalled();
  });
});
