import {
  DESIGN_MODEL_BLEND_MODES,
  DESIGN_MODEL_EFFECT_SCHEMA,
  DESIGN_MODEL_NODE_PROPERTY_PATCH_SCHEMA,
} from "./design-agent-operation-schemas";

export const DESIGN_COMPONENT_TOOL_INPUT_SCHEMA = {
  type: "object",
  description:
    "Create and place linked components, combine inspected sibling Component Mains into a Figma-compatible Component Set with explicit unique VARIANT values, author and reorder Boolean/Text/Instance-swap/Slot properties on explicit Main sublayers, edit/reset/clear Slot contents and guidance settings, set/reset typed instance and VARIANT property values, use advanced sourcePath overrides, detach an instance, or locate its Main. Component, set, root, property IDs, and existing property order must come from inspection.",
  properties: {
    action: {
      description:
        "Choose one action. create-component requires exactly action, label, pageId, rootNodeId, componentId, and name; rootNodeId is the existing inspected Frame/Group promoted as the Main.",
      enum: [
        "create-component",
        "create-instance",
        "remove-component",
        "combine-as-variants",
        "add-component-to-variant-set",
        "duplicate-variant",
        "remove-variant",
        "dissolve-variant-set",
        "add-variant-property",
        "rename-variant-property",
        "reorder-variant-properties",
        "remove-variant-property",
        "rename-variant-value",
        "reorder-variant-values",
        "set-variant-properties",
        "add-property",
        "rename-property",
        "reorder-properties",
        "remove-property",
        "set-property",
        "reset-property",
        "create-slot-override",
        "clear-slot",
        "reset-slot",
        "set-slot-settings",
        "set-override",
        "reset-overrides",
        "detach-instance",
        "go-to-main",
      ],
    },
    label: { type: "string", minLength: 1, maxLength: 256 },
    pageId: { type: "string", minLength: 1, maxLength: 256 },
    componentId: { type: "string", minLength: 1, maxLength: 256 },
    componentIds: {
      type: "array",
      minItems: 2,
      maxItems: 128,
      uniqueItems: true,
      items: { type: "string", minLength: 1, maxLength: 256 },
    },
    componentRootNodeIds: {
      type: "array",
      minItems: 2,
      maxItems: 128,
      uniqueItems: true,
      items: { type: "string", minLength: 1, maxLength: 256 },
    },
    componentRootNodeId: { type: "string", minLength: 1, maxLength: 256 },
    sourceComponentId: { type: "string", minLength: 1, maxLength: 256 },
    sourceRootNodeId: { type: "string", minLength: 1, maxLength: 256 },
    variantSetId: { type: "string", minLength: 1, maxLength: 256 },
    rootNodeId: {
      type: "string",
      minLength: 1,
      maxLength: 256,
      description:
        "Existing inspected root for create-component and Component Set actions. Never substitute nodeId or componentRootNodeId for create-component.",
    },
    variantPropertiesByComponentId: {
      type: "object",
      minProperties: 2,
      maxProperties: 128,
      additionalProperties: {
        type: "object",
        minProperties: 1,
        maxProperties: 128,
        additionalProperties: {
          type: "string",
          minLength: 1,
          maxLength: 256,
        },
      },
    },
    variantProperties: {
      type: "object",
      minProperties: 1,
      maxProperties: 128,
      additionalProperties: { type: "string", minLength: 1, maxLength: 256 },
    },
    valuesByComponentId: {
      type: "object",
      minProperties: 1,
      maxProperties: 128,
      additionalProperties: { type: "string", minLength: 1, maxLength: 256 },
    },
    propertyOrder: {
      type: "array",
      minItems: 1,
      maxItems: 128,
      uniqueItems: true,
      items: { type: "string", minLength: 1, maxLength: 256 },
    },
    componentPropertyOrder: {
      type: "array",
      minItems: 1,
      maxItems: 4096,
      uniqueItems: true,
      items: { type: "string", minLength: 1, maxLength: 512 },
    },
    values: {
      type: "array",
      minItems: 1,
      maxItems: 1024,
      uniqueItems: true,
      items: { type: "string", minLength: 1, maxLength: 256 },
    },
    instanceId: { type: "string", minLength: 1, maxLength: 256 },
    name: { type: "string", minLength: 1, maxLength: 256 },
    propertyId: { type: "string", minLength: 1, maxLength: 256 },
    propertyName: { type: "string", minLength: 1, maxLength: 512 },
    type: { enum: ["BOOLEAN", "TEXT", "INSTANCE_SWAP", "SLOT"] },
    sourceNodeId: { type: "string", minLength: 1, maxLength: 256 },
    preferredValues: {
      type: "array",
      maxItems: 256,
      items: {
        type: "object",
        properties: {
          type: { enum: ["COMPONENT", "COMPONENT_SET"] },
          key: { type: "string", minLength: 1, maxLength: 256 },
        },
        required: ["type", "key"],
        additionalProperties: false,
      },
    },
    settings: {
      type: "object",
      properties: {
        stretchChildOnInsert: { type: "boolean" },
        displayEmptyByDefault: { type: "boolean" },
        minChildren: {
          anyOf: [
            { type: "integer", minimum: 0, maximum: 4096 },
            { type: "null" },
          ],
        },
        maxChildren: {
          anyOf: [
            { type: "integer", minimum: 0, maximum: 4096 },
            { type: "null" },
          ],
        },
        allowPreferredValuesOnly: { type: "boolean" },
      },
      additionalProperties: false,
    },
    description: { type: "string", maxLength: 2000 },
    value: {
      anyOf: [{ type: "boolean" }, { type: "string", maxLength: 100_000 }],
    },
    parentId: {
      anyOf: [
        { type: "string", minLength: 1, maxLength: 256 },
        { type: "null" },
      ],
    },
    index: { type: "integer", minimum: 0 },
    x: { type: "number" },
    y: { type: "number" },
    sourcePath: {
      type: "array",
      minItems: 1,
      maxItems: 64,
      items: { type: "string", minLength: 1, maxLength: 256 },
    },
    patch: {
      type: "object",
      minProperties: 1,
      properties: {
        name: { type: "string" },
        visible: { type: "boolean" },
        opacity: { type: "number", minimum: 0, maximum: 1 },
        blendMode: { enum: DESIGN_MODEL_BLEND_MODES },
        effects: { type: "array", items: DESIGN_MODEL_EFFECT_SCHEMA },
        maskMode: {
          enum: ["none", "alpha", "luminance", "clipping", "outline"],
        },
        properties: DESIGN_MODEL_NODE_PROPERTY_PATCH_SCHEMA,
      },
      additionalProperties: false,
    },
  },
  required: ["action", "pageId"],
  additionalProperties: false,
} as const;
